name: fair_dart2js
description: Convert individual dart file to js.
version: 1.3.2
homepage: https://fair.58.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  analyzer: ^2.3.0
  path: ^1.8.0